name: Report Functional Bug 🐞
description: |
  Functional bugs affect operation or stability of the driver and/or hardware.
  Before filling out, check if your issue has already been reported.
  Read CONTRIBUTING.md.
  Thank you!
body:
- type: input
  id: sw_driver_version
  attributes:
    label: NVIDIA OpenRM Driver version
    description: "Which OpenRM driver version are you running? Be as specific as possible: SHA is best when built from specific commit."
  validations:
    required: true
- type: dropdown
  id: sw_driver_proprietary
  attributes:
    label: "Does this happen with the proprietary driver (of the same version) as well?"
    options:
    - "Yes"
    - "No"
    - "I cannot test this"
  validations:
    required: true
- type: input
  id: sw_host_os
  attributes:
    label: Operating System and Version
    description: "Which OS are you running this on? For example: Debian 11"
  validations:
    required: true
- type: input
  id: hw_gpu_type
  attributes:
    label: "Hardware: GPU"
    description: "Which GPU is this bug manifesting with (name multiple or N/A if it happens without a GPU too)?"
  validations:
    required: true
- type: textarea
  id: bug_description
  attributes:
    label: "Describe the bug"
    description: "Please write a clear and concise description of what the bug is."
  validations:
    required: true
- type: textarea
  id: bug_repro
  attributes:
    label: "To Reproduce"
    description: "Please provide bullet-pointed reproduction steps, so we can see the issue on our end. Name all required preconditions."
  validations:
    required: true
- type: dropdown
  id: bug_incidence
  attributes:
    label: "Bug Incidence"
    description: "How often does the issue happen?"
    options:
    - Once
    - Sometimes
    - Always
  validations:
    required: true
- type: textarea
  id: bug_expected_behaviour
  attributes:
    label: "Expected behaviour"
    description: "If unclear from the above: What did you expect to happen instead?"
  validations:
    required: false
- type: markdown
  attributes:
    value: |
      **Please reproduce the problem, run nvidia-bug-report.sh, and attach the resulting nvidia-bug-report.log.gz to this issue (you can only do this after submitting this issue form).**

