blank_issues_enabled: false
contact_links:
  - name: Unsure?
    url: https://github.com/NVIDIA/open-gpu-kernel-modules/discussions/categories/general
    about: Unsure of what to click, where to go, what the process for your thing is? We're happy to help. Click to visit the discussion board and say hello!
  - name: Report Proprietary Driver Bug
    url: https://forums.developer.nvidia.com/c/gpu-graphics/linux/148
    about: Bugs that aren't specific to the open source driver in this repository should be reported with the linked forums instead. If you are unsure on what kind of bug you have, feel free to open a thread in Discussions. We're here to help!
  - name: Suggest Feature
    url: https://github.com/NVIDIA/open-gpu-kernel-modules/discussions/categories/features
    about: Please do not open Issues for feature requests; instead, suggest and discuss new features on the Github discussion board. If you have a feature you worked on and want to PR it, please also open a discussion before doing so. There are pinned threads on the Feature discussion board; please read them.
