blank_issues_enabled: false
contact_links:
  - name: Report Proprietary Driver Bug
    url: https://forums.developer.nvidia.com/c/gpu-graphics/linux/148
    about: Bugs that aren't specific to the OpenRM driver in this repository should be reported with the linked forums instead. If you are unsure, feel free to open a thread in Discussions. We're here to help!
  - name: Suggest Feature
    url: https://github.com/NVIDIA/open-gpu-kernel-modules/discussions/categories/features
    about: Please suggest and discuss new features on the Github discussion board. If you have a feature you worked on and want to PR it, please also open a discussion before doing so. There are pinned threads on the Feature discussion board; please read them.
  - name: Report Confidential Issue
    url: https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/SECURITY.md
    about: Please see SECURITY.md for instructions on how to report confidential issues, including security vulnerabilities.
